### ISSUE TITLE
多了中划线

### ISSUE THREAD

**Issue by mw986381673** [pingcap/docs-dm#535]
File: [/zh/command-line-flags.md](https://docs.pingcap.com/zh/tidb-data-migration/stable/command-line-flags)
--initial-cluster

在未指定 join 参数时需要指定该参数。一个 3 节点集群的配置示例为 "dm-master-1=http://172.16.15.11:8291,dm-master-2-=http://172.16.15.12:8291,dm-master-3=http://172.16.15.13:8291"
dm-master-2-=http://172.16.15.12:8291 多了-
dm-master-2=http://172.16.15.12:8291

**Comment by CharLotteiu** [comment]
@csuzhangxc PTAL. Thx!

**Comment by csuzhangxc** [comment]
@mw986381673 方便帮忙提个 PR 修一下吗
