### ISSUE TITLE
security的配置不明

### ISSUE THREAD

**Issue by coderplay** [pingcap/docs-dm#607]
File: [/zh/source-configuration-file.md](https://docs.pingcap.com/zh/tidb-data-migration/dev/source-configuration-file)

```
 security:                       # 上游数据库 TLS 相关配置                             
    ssl-ca: "/path/to/ca.pem"
    ssl-cert: "/path/to/cert.pem"
    ssl-key: "/path/to/key.pem"
```

文档没有说明这些`/path/to`是在哪个component上的的path. 是dm master的path， 还是dm worker的path, 还是别的instance的path?

**Comment by lance6716** [comment]
以`/`开头的是绝对路径

it's absolute path because it starts with `/`

**Comment by coderplay** [comment]
![confused](http://5b0988e595225.cdn.sohucs.com/images/20181020/84d176465ef34eed965988568efe13b6.jpeg)

**Comment by lance6716** [comment]
抱歉，刚明白过来。dm master 和 dm worker 都可能通过证书访问集群，证书要保证他们都能访问。

可以提个 PR 帮我们修改文档吗

**Comment by yikeke** [comment]
@CharLotteiu 帮忙跟进改下吧
