### ISSUE TITLE
已经不是最新版地址了

### ISSUE THREAD

**Issue by luisxin** [pingcap/docs-dm#694]
File: [/zh/quick-start-with-dm.md](https://docs.pingcap.com/zh/tidb-data-migration/stable/quick-start-with-dm)

**Comment by CharLotteiu** [comment]
@lance6716 Please take a look. Thanks!

**Comment by lance6716** [comment]
请问“最新版地址”指的是什么

**Comment by lance6716** [comment]
closed due to no response
