### ISSUE TITLE
命令行示例

### ISSUE THREAD

**Issue by 15767637775** [pingcap/docs-dm#769]
File: [/zh/manually-handling-sharding-ddl-locks.md](https://docs.pingcap.com/zh/tidb-data-migration/stable/manually-handling-sharding-ddl-locks)

unlock-ddl-lock test-`shard_db`.`shard_table`
应该写
unlock-ddl-lock test-\`shard_db\`.\`shard_table\`
不然shell命令行执行报错， 一脸懵

**Comment by 15767637775** [comment]
\转义字符。。。。又没了

**Comment by TomShawn** [comment]
@Liuxiaozhen12 PTAL and help create a JIRA issue. Thanks!

**Comment by Liuxiaozhen12** [comment]
本文档的命令在交互模式中进行，因此在命令示例中未添加转义字符。我们已修改文档，感谢您的反馈！
