### ISSUE TITLE
"some DDLs still need to be copied." is unclear for me

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs-dm#886]
File: [/release-5.3/en/feature-online-ddl.md](https://docs.pingcap.com/tidb-data-migration/stable/feature-online-ddl)

I'd like to know if my understanding is correct.
Does "some DDLs still need to be copied." mean "some DDLs still need (tables) to be copied. "?

**Comment by shichun-0415** [comment]
@yahonda Thanks for your feedback. @lichunzhu Could you take a look at this issue? Thanks.

**Comment by lichunzhu** [comment]
@yahonda I have checked this document. This part introduces MySQL online ddl's background. It should be:

DDL statements are always used in the database applications. MySQL 5.6 and later versions support online-ddl feature, but there are limitations for usage. For example, ~~to acquire the MDL lock, some DDLs still need to be copied~~ sometimes executing these DDLs will acquire the MDL lock. Some DDLs will copy the whole table. In production scenarios, the table lock during DDL execution can block the reads or writes to and from the database to a certain extent.

**Comment by shichun-0415** [comment]
@lichunzhu Thanks for clarifying. @yahonda I will modify the doc as "some DDLs still need tables to be copied".

**Comment by yahonda** [comment]
> I will modify the doc as "some DDLs still need tables to be copied".

Looks good!

**Comment by shichun-0415** [comment]
Seems the problem has been resolved. Shall we close this issue? @yahonda

**Comment by yahonda** [comment]
https://github.com/pingcap/docs-dm/pull/887/files looks great. I am closing this issue. Thanks for the help.
